// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfikwvrewudwrkyyerup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmaWt3dnJld3Vkd3JreXllcnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTA3MTQsImV4cCI6MjA3MTk2NjcxNH0.eRFNc2cZ7ytTRzONQT0EWaxe4A_Pc3sw8WGuymKUFsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});